### ISSUE TITLE
Why not on NuGet?

### ISSUE THREAD

**Issue by matsu-zaka-sa-tou** [davidbritch/dotnet-maui-videoplayer#8]
I tried pack it into a nuget package but it has some error, so I wonder when we will be able to see a nuget package.

**Comment by 99067718** [comment]
I guess he wants to make some finishing touches before uploading it as a NuGet package

**Comment by EdwardMcFlurry** [comment]
@davidbritch can you please make us aware if you have packed it as Nuget Package 🙏🏻

**Comment by davidbritch** [comment]
The bad news: from day one I wrote it to learn about how to write handlers, rather than to be a fully functioning video playback library. Hence I decided not to package it for NuGet.

The good news: A `MediaElement` type, which'll play video and audio, is coming to .NET MAUI Community Toolkit soon. See https://github.com/CommunityToolkit/Maui/pull/667 for more info.
